import type { LoanType } from "@/types/loan";

export const loanTypes: LoanType[] = [
  {
    id: "small_business_micro",
    name: "Small Business Micro Loan",
    category: "small_business",
    minAmount: 30000,
    maxAmount: 100000,
    termLimitDays: 30,
    processingFeeRate: 5,
    penaltyFeeRate: 2,
    description:
      "Quick loans for small business owners with flexible repayment",
  },
  {
    id: "small_business_standard",
    name: "Small Business Standard Loan",
    category: "small_business",
    minAmount: 100000,
    maxAmount: 500000,
    termLimitDays: 60,
    processingFeeRate: 4,
    penaltyFeeRate: 1.5,
    description: "Standard business loans for established small businesses",
  },
  {
    id: "market_women_daily",
    name: "Market Women Daily Loan",
    category: "market_women",
    minAmount: 20000,
    maxAmount: 80000,
    termLimitDays: 21,
    processingFeeRate: 6,
    penaltyFeeRate: 3,
    description: "Daily collection loans for market traders",
  },
  {
    id: "market_women_weekly",
    name: "Market Women Weekly Loan",
    category: "market_women",
    minAmount: 50000,
    maxAmount: 200000,
    termLimitDays: 28,
    processingFeeRate: 5,
    penaltyFeeRate: 2.5,
    description: "Weekly collection loans for market women",
  },
  {
    id: "salary_earners",
    name: "Salary Earners Loan",
    category: "salary_earners",
    minAmount: 100000,
    maxAmount: 1000000,
    termLimitDays: 90,
    processingFeeRate: 3,
    penaltyFeeRate: 1,
    description: "Loans for salary earners with monthly repayment",
  },
  {
    id: "student_loan",
    name: "Student Emergency Loan",
    category: "students",
    minAmount: 15000,
    maxAmount: 50000,
    termLimitDays: 45,
    processingFeeRate: 2,
    penaltyFeeRate: 1,
    description: "Emergency loans for students",
  },
];
