import type {
  CreditOfficer,
  Customer,
  RepaymentSchedule,
  LoanDetails,
} from "@/types/loan-system";

export const mockCreditOfficers: CreditOfficer[] = [
  {
    id: "co1",
    name: "John Adebayo",
    email: "john.adebayo@financelend.com",
    phone: "+234-801-234-5678",
    department: "Retail Banking",
    employeeId: "FL001",
    totalLoansManaged: 45,
    activeLoans: 23,
  },
  {
    id: "co2",
    name: "Sarah Okafor",
    email: "sarah.okafor@financelend.com",
    phone: "+234-802-345-6789",
    department: "Commercial Banking",
    employeeId: "FL002",
    totalLoansManaged: 38,
    activeLoans: 19,
  },
  {
    id: "co3",
    name: "Michael Emeka",
    email: "michael.emeka@financelend.com",
    phone: "+234-803-456-7890",
    department: "SME Banking",
    employeeId: "FL003",
    totalLoansManaged: 52,
    activeLoans: 31,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    name: "Jane Smith",
    email: "jane.smith@email.com",
    phone: "+234-901-234-5678",
    address: "123 Victoria Island, Lagos",
    creditOfficerId: "co1",
  },
  {
    id: "c2",
    name: "John Doe",
    email: "john.doe@email.com",
    phone: "+234-902-345-6789",
    address: "456 Ikeja GRA, Lagos",
    creditOfficerId: "co1",
  },
  {
    id: "c3",
    name: "Michael Johnson",
    email: "michael.johnson@email.com",
    phone: "+234-903-456-7890",
    address: "789 Abuja Central, FCT",
    creditOfficerId: "co2",
  },
  {
    id: "c4",
    name: "Sarah Wilson",
    email: "sarah.wilson@email.com",
    phone: "+234-904-567-8901",
    address: "321 Port Harcourt, Rivers",
    creditOfficerId: "co3",
  },
];

export const mockRepaymentSchedules: RepaymentSchedule[] = [
  {
    id: "r1",
    loanNo: "#LON-0002",
    customerId: "c1",
    customerName: "Jane Smith",
    loanIssuedDate: "2024-06-01",
    repaymentDate: "2024-12-25", // Future date for schedule
    loanDeadline: "2024-12-31",
    principalAmount: 198000,
    processingFee: 22917,
    penalty: 0,
    totalAmount: 220917,
    amountLeftToPay: 50000,
    dueToday: 10000,
    status: "under repayment",
    fullyPaid: false,
    creditOfficerId: "co1",
    loanType: "Mortgage Loan",
  },
  {
    id: "r2",
    loanNo: "#LON-0003",
    customerId: "c2",
    customerName: "John Doe",
    loanIssuedDate: "2024-07-01",
    repaymentDate: "2024-12-26", // Future date for schedule
    loanDeadline: "2024-12-31",
    principalAmount: 900,
    processingFee: 31.5,
    penalty: 0,
    totalAmount: 931.5,
    amountLeftToPay: 500,
    dueToday: 500,
    status: "under repayment",
    fullyPaid: false,
    creditOfficerId: "co1",
    loanType: "Personal Loan",
  },
  {
    id: "r3",
    loanNo: "#LON-0004",
    customerId: "c3",
    customerName: "Michael Johnson",
    loanIssuedDate: "2024-06-15",
    repaymentDate: "2024-12-27", // Future date for schedule
    loanDeadline: "2024-08-15",
    principalAmount: 35714,
    processingFee: 2500,
    penalty: 1200,
    totalAmount: 39414,
    amountLeftToPay: 39414,
    dueToday: 5000,
    status: "overdue",
    fullyPaid: false,
    creditOfficerId: "co2",
    loanType: "Business Loan",
  },
  {
    id: "r4",
    loanNo: "#LON-0005",
    customerId: "c4",
    customerName: "Sarah Wilson",
    loanIssuedDate: "2024-08-01",
    repaymentDate: "2024-12-28", // Future date for schedule
    loanDeadline: "2024-09-01",
    principalAmount: 50000,
    processingFee: 3750,
    penalty: 0,
    totalAmount: 53750,
    amountLeftToPay: 53750,
    dueToday: 53750,
    status: "approved",
    fullyPaid: false,
    creditOfficerId: "co3",
    loanType: "Vehicle Loan",
  },
];

export const mockPaymentHistory: RepaymentSchedule[] = [
  {
    id: "p1",
    loanNo: "#LON-0002",
    customerId: "c1",
    customerName: "Jane Smith",
    loanIssuedDate: "2024-06-01",
    repaymentDate: "2024-12-20", // Recent payment
    loanDeadline: "2024-12-31",
    principalAmount: 198000,
    processingFee: 22917,
    penalty: 8793.97,
    totalAmount: 229710.97,
    amountLeftToPay: 0,
    dueToday: 0,
    status: "fully paid",
    fullyPaid: true,
    creditOfficerId: "co1",
    loanType: "Mortgage Loan",
  },
  {
    id: "p2",
    loanNo: "#LON-0003",
    customerId: "c2",
    customerName: "John Doe",
    loanIssuedDate: "2024-07-01",
    repaymentDate: "2024-12-15", // Older payment
    loanDeadline: "2024-12-31",
    principalAmount: 900,
    processingFee: 31.5,
    penalty: 0,
    totalAmount: 931.5,
    amountLeftToPay: 431.5,
    dueToday: 0,
    status: "under repayment",
    fullyPaid: false,
    creditOfficerId: "co1",
    loanType: "Personal Loan",
  },
];

export const mockLoanDetails: Record<string, LoanDetails> = {
  "LON-0002": {
    ...mockRepaymentSchedules[0],
    from: {
      company: "FinanceLend Nigeria Ltd",
      phone: "+234-700-FINANCE",
      email: "info@financelend.ng",
    },
    to: {
      name: "Jane Smith",
      phone: "+234-901-234-5678",
      address: "123 Victoria Island, Lagos",
    },
    paymentHistory: mockPaymentHistory.filter((p) => p.loanNo === "#LON-0002"),
    creditOfficer: mockCreditOfficers[0],
  },
  "LON-0003": {
    ...mockRepaymentSchedules[1],
    from: {
      company: "FinanceLend Nigeria Ltd",
      phone: "+234-700-FINANCE",
      email: "info@financelend.ng",
    },
    to: {
      name: "John Doe",
      phone: "+234-902-345-6789",
      address: "456 Ikeja GRA, Lagos",
    },
    paymentHistory: mockPaymentHistory.filter((p) => p.loanNo === "#LON-0003"),
    creditOfficer: mockCreditOfficers[0],
  },
};
